### ISSUE TITLE
use axios everywhere

### ISSUE THREAD

**Issue by prajjwalyd** [SundarbansWebOps/Frontend#28]

**Comment by dedWalker18** [comment]
I would like to work on this!

**Comment by ravikumawat7716** [comment]
Hey @dedWalker18 
You can start working on this. 
Find all the API Calls & implement them with axios if there are implemented using fetch api or another ways.
Update your work progress in comments.

**Comment by dedWalker18** [comment]
on it @ravikumawat7716. got a little delayed because of vivas. will submit it soon.
