### ISSUE TITLE
use tailwind cli

### ISSUE THREAD

**Issue by prajjwalyd** [SundarbansWebOps/Frontend#29]

**Comment by ravikumawat7716** [comment]
@kisharnath , @baaz1708 , @prajjwalyd , @kharramahendra 
Anyone who can work on this?

**Comment by kisharnath** [comment]
@ravikumawat7716  I will send pull request. I saw some inline classes are implemented we should use tailwind classes .

**Comment by ravikumawat7716** [comment]
Okay , Go ahead.

Check this issue as well : https://github.com/SundarbansWebOps/Frontend/issues/29

Try to add tailwind cli , so can can remove the tailwind cdn.

Anyone who can implement this ?
We are open for contributions.

**Comment by kisharnath** [comment]
I will add the cli part

**Comment by prajjwalyd** [comment]
Hey @kisharnath, are you still interested in working on this?

**Comment by kisharnath** [comment]
Yes , I was quite busy . I will send a pr this month is that fine?

**Comment by ravikumawat7716** [comment]
Thank you so much @kisharnath
